import { defineConfig } from "tsup"

export default defineConfig({
  entry: {
    index: "src/index.ts",
    cli: "src/cli.ts",
    "registry/index": "src/registry/index.ts",
    "registry/schema": "src/registry/schema.ts",
    "utils/index": "src/utils/index.ts",
    colors: "src/colors.ts",
    "preset/index": "src/preset/index.ts",
    "mcp/index": "src/mcp/index.ts",
    "icons/index": "src/icons/index.ts",
  },
  format: ["esm"],
  dts: true,
  clean: true,
  outDir: "dist",
  external: [
    "react",
    "react-native",
    "nativewind",
    "tailwindcss",
    "commander",
    "cosmiconfig",
    "zod",
    "@modelcontextprotocol/sdk",
    "chalk",
    "dedent",
    "diff",
    "execa",
    "fast-glob",
    "fs-extra",
    "fuzzysort",
    "ora",
    "postcss",
    "prompts",
    "recast",
    "tailwind-merge",
    "ts-morph",
    "zod-to-json-schema",
  ],
  splitting: false,
  sourcemap: true,
  minify: false,
})
